#====================================================================================
#
#
#               MK-Spawn    Plugin Configuration
#                                 插件设置
#
#                                             Author: Mu_Cloud
#                                              作者
#
#====================================================================================

# 插件设置文件版本
# 注意！！！ 请勿更改此项！！！
Version: 1.1.0

# 是否进行自动更新
Auto-Update: false

Settings:

  # 语言文件设置
  # 具体格式请参阅 locale 文件夹内 Lang.zh_CN.yml
  Language: zh_CN

  # 传送间隔时间，以秒为单位
  CoolingDown: 3

  # 是否使用 GUI 模式
  GUIMode: true

  # 是否使用牌子用于地标传送
  UseSignWarp: true

