#--------------------------------------------------------------------------
name: EX-AdvancedWarps
description: A patch and extension plugin for Essentials.
main: me.mangomilktea.plugin.EX.AdvancedWarps.Main
version: 1.0.0.Beta7
#--------------------------------------------------------------------------
author: Mango_MilkTea
website: https://gitee.com/mango_milktea/ex-advancedwarps
api-version: "1.13"
depend: [Essentials,Vault]
loadbefore: [Essentials]

commands:
  AdvancedWarps:
    description: Reload command.
    usage: /aw [info/reload]
    aliases: [advancedwarps,aw,exaw]
  warp:
    description: command form Essentials.
    usage: /warp
    aliases: [warps]

permissions:
  advancedwarps.admin:
    description: main permission.
    default: op
  exaw.teleportwarp.bypass.*:
    description: Teleport bypass.
    default: op