#--------------------------------------------------------------------------
name: EX-AdvancedWarps
description: A patch and extension for Essentials.
main: me.markchanel.plugin.EX.AdvancedWarps.Main
#--------------------------------------------------------------------------
website: https://gitee.com/markchanel/ex-advancedwarps
author: Mark_Chanel
version: 1.0.0.Beta1
api-version: "1.13"
depend: [Essentials,Vault]
loadbefore: [Essentials]

commands:
  AdvancedWarps:
    description: Reload command.
    usage: /aw [info/reload]
    aliases: [advancedwarps,aw,exaw]
  warp:
    description: command form Essentials.
    usage: /warp
    aliases:
      - warps

permissions:
  advancedwarps.admin:
    description: main permission.
    default: op
